### ISSUE TITLE
About madeintanzania/guide

### ISSUE THREAD

**Issue by alphaolomi** [madeintanzania/guide#1]
Hey @piusalfred 

I hope you are doing well

So I just was you created  https://github.com/madeintanzania/guide i just wanted to let you know there is https://github.com/Tanzania-Developers-Community/made-in-tanzania

Backed up by TDC a welcoming, active growing community of developers in Tanzania.

If you think there is something missing consider reaching out, opening an issue or submitting PRs for contributions

Reach out through https://t.me/tanzaniadeveloperscommunity, 

- Alpha

**Comment by piusalfred** [comment]
Thanks for reaching out. This is appreciated. I did get a look and sure enough, you did a great job.
